import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "@mfezones/ui";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Client App</a>
        </h1>
        <Button href="" variant="contained">
          Client button!
        </Button>
      </main>
    </div>
  );
};

export default Home;
