import type { NextPage } from "next";
import Head from "next/head";
import { Button, DogCard, Grid } from "@mfezones/ui";
import dogs from "@formidable/dogs";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Client app: check these dogs!</h1>
        <div>
          <Grid container spacing={2}>
            {dogs.map((dog) => (
              <Grid item key={dog.imageUrl} xs={12} sm={6} md={4}>
                <DogCard
                  imageUrl={dog.imageUrl}
                  name={<Link href={`/dogs/${dog.name}`}>{dog.name}</Link>}
                  description={dog.description}
                />
              </Grid>
            ))}
          </Grid>
        </div>
        <Button href="" variant="contained">
          Client button!
        </Button>
      </main>
    </div>
  );
};

export default Home;
