import type { NextPage } from "next";
import Head from "next/head";
import { Button, Typography } from "@mfezones/ui";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Typography variant="h1" gutterBottom>
          Admin Portal
        </Typography>
        <Typography gutterBottom sx={{ marginBottom: 4 }}>
          A third, separate app stitched together with Zones.
        </Typography>

        <Button href="/app" variant="contained">
          Check out the pups!
        </Button>
      </main>
    </div>
  );
};

export default Home;
