import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import { Button } from "@mfezones/ui";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Admin App</a>
        </h1>

        <div>
          <Link href="/users">
            <a>
              <h2>View and Manage Users</h2>
            </a>
          </Link>

          <Link href="/posts">
            <a>
              <h2>View and Manage Posts</h2>
            </a>
          </Link>
        </div>
        <Button href="" variant="contained">
          Admin button!
        </Button>
      </main>
    </div>
  );
};

export default Home;
